//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class VOState {
	public delegate void StateChangeDelegate();

	public	int 					id;
	public	List<int>				from;

	public	StateChangeDelegate 	enter;
	public	StateChangeDelegate 	update;
	public	StateChangeDelegate 	exit;

	public VOState (int id, List<int> from, StateChangeDelegate enter, StateChangeDelegate update, StateChangeDelegate exit) {
		this.id 	= id;
		this.from 	= from;
		this.enter 	= enter;
		this.update = update;
		this.exit 	= exit;
	}
}

