//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class VOEventToListener {
	
	public int 					EventID;
	public EventBus.Listener 	Listener;

	public VOEventToListener (int eventID, EventBus.Listener listener) {
		this.EventID = eventID;
		this.Listener = listener;
	}
}

