//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class VOTile {

	public 			int row;
	public 			int column;
	public 			int value;

	public 			int state;

	public static 	int STATE_IDLE 		= 1;
	public static 	int STATE_SPAWN		= 2;
	public static 	int STATE_DIE		= 3;
	public static 	int STATE_ANIMATING = 4;
	public static 	int STATE_MOVING	= 5;

	public VOTile (int row, int column, int value) {
		this.row = row;
		this.column = column;
		this.value = value;

		state = STATE_SPAWN;
	}
}

